// gen-lucide.mjs — generate a narrow lucide-react barrel from the icons an app slice actually imports.
//
// WHY this exists (replaces the hand-drawn stubs/lucide-react.tsx): esbuild parses lucide's 1000+-icon
// barrel once per importing module, which hangs the preview compile on a memory-constrained box. The old
// fix was 21 hand-inlined SVGs — accurate but hand-maintained, so every icon a component newly imports
// broke the build with "No matching export" (it did, on 2026-08-19: GraduationCap, Briefcase, ShieldCheck,
// Radar). Five apps import 133 distinct icon sites; hand-maintaining that is not viable.
//
// Instead: scan the slice's source roots for `lucide-react` imports, resolve each name to lucide's OWN
// per-icon ESM module (dist/esm/icons/<kebab>.mjs), and emit a barrel that re-exports just those. Real
// glyphs, no 1000-module parse, and a new icon import needs no edit here — the next build picks it up.
//
// Absolute paths in the emitted re-exports: the barrel lands in packages/ui/dist, which has no
// lucide-react of its own, so bare-specifier resolution would fail.

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/** `GraduationCap` → `graduation-cap`, `Building2` → `building-2`, `CircleCheckBig` → `circle-check-big`. */
export function iconFileName(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Za-z])([0-9])/g, '$1-$2')
    .toLowerCase();
}

const SRC_RE = /\.(tsx?|jsx?|mts|mjs)$/;

function walk(dir, out) {
  if (!existsSync(dir)) return out;
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) {
      if (e.name === 'node_modules' || e.name === '.next' || e.name === 'dist') continue;
      walk(p, out);
    } else if (SRC_RE.test(e.name)) out.push(p);
  }
  return out;
}

// `import { A, B as C, type D } from "lucide-react"` — the specifier list, however it's wrapped.
const IMPORT_RE = /import\s+(?:type\s+)?\{([^}]*)\}\s*from\s*["']lucide-react["']/g;

/** Every identifier imported from lucide-react anywhere under `roots`. Aliases resolve to the SOURCE name. */
export function scanLucideNames(roots) {
  const names = new Set();
  for (const root of roots) {
    for (const file of walk(root, [])) {
      const src = readFileSync(file, 'utf8');
      for (const m of src.matchAll(IMPORT_RE)) {
        for (const raw of m[1].split(',')) {
          const spec = raw.trim().replace(/^type\s+/, '');
          if (!spec) continue;
          const name = spec.split(/\s+as\s+/)[0].trim();
          if (/^[A-Z][A-Za-z0-9]*$/.test(name)) names.add(name);
        }
      }
    }
  }
  return [...names].sort();
}

/**
 * Write the barrel. Returns {file, resolved, unresolved} — `unresolved` are names with no icon module
 * (lucide's own type exports like `LucideIcon`/`LucideProps`, which are erased at build time, plus any
 * genuine typo). The caller decides whether an unresolved name is fatal.
 */
export function generateLucideBarrel({ roots, lucideRoot, outFile }) {
  const iconsDir = join(lucideRoot, 'dist', 'esm', 'icons');
  if (!existsSync(iconsDir)) throw new Error(`lucide icons dir not found: ${iconsDir}`);
  const names = scanLucideNames(roots);
  const resolved = [];
  const unresolved = [];
  const lines = [
    '// GENERATED by .design-sync/lib/gen-lucide.mjs — do not edit. Re-exports the icons this app imports',
    "// from lucide-react's own per-icon modules, so the glyphs are real and the barrel stays small.",
  ];
  for (const name of names) {
    const abs = join(iconsDir, `${iconFileName(name)}.mjs`);
    if (!existsSync(abs)) { unresolved.push(name); continue; }
    resolved.push(name);
    lines.push(`export { default as ${name} } from ${JSON.stringify(abs.split('\\').join('/'))};`);
  }
  writeFileSync(outFile, lines.join('\n') + '\n');
  return { file: outFile, resolved, unresolved };
}
